QT.quickcontrols2basicstyleimpl_private.VERSION = 6.9.3
QT.quickcontrols2basicstyleimpl_private.name = QtQuickControls2BasicStyleImpl
QT.quickcontrols2basicstyleimpl_private.module =
QT.quickcontrols2basicstyleimpl_private.libs = $$QT_MODULE_LIB_BASE
QT.quickcontrols2basicstyleimpl_private.includes = $$QT_MODULE_LIB_BASE/QtQuickControls2BasicStyleImpl.framework/Versions/A/Headers/6.9.3 $$QT_MODULE_LIB_BASE/QtQuickControls2BasicStyleImpl.framework/Versions/A/Headers/6.9.3/QtQuickControls2BasicStyleImpl
QT.quickcontrols2basicstyleimpl_private.frameworks = 
QT.quickcontrols2basicstyleimpl_private.depends = quickcontrols2basicstyleimpl
QT.quickcontrols2basicstyleimpl_private.uses = 
QT.quickcontrols2basicstyleimpl_private.module_config = v2 lib_bundle internal_module
QT.quickcontrols2basicstyleimpl_private.enabled_features = 
QT.quickcontrols2basicstyleimpl_private.disabled_features = 
