QT.quickcontrols2iosstyleimpl_private.VERSION = 6.9.3
QT.quickcontrols2iosstyleimpl_private.name = QtQuickControls2IOSStyleImpl
QT.quickcontrols2iosstyleimpl_private.module =
QT.quickcontrols2iosstyleimpl_private.libs = $$QT_MODULE_LIB_BASE
QT.quickcontrols2iosstyleimpl_private.includes = $$QT_MODULE_LIB_BASE/QtQuickControls2IOSStyleImpl.framework/Versions/A/Headers/6.9.3 $$QT_MODULE_LIB_BASE/QtQuickControls2IOSStyleImpl.framework/Versions/A/Headers/6.9.3/QtQuickControls2IOSStyleImpl
QT.quickcontrols2iosstyleimpl_private.frameworks = 
QT.quickcontrols2iosstyleimpl_private.depends = quickcontrols2iosstyleimpl
QT.quickcontrols2iosstyleimpl_private.uses = 
QT.quickcontrols2iosstyleimpl_private.module_config = v2 lib_bundle internal_module
QT.quickcontrols2iosstyleimpl_private.enabled_features = 
QT.quickcontrols2iosstyleimpl_private.disabled_features = 
